// Generated by https://quicktype.io

export interface PropertyResponse {
  content:          Property[];
  pageable:         Pageable;
  totalPages:       number;
  totalElements:    number;
  last:             boolean;
  size:             number;
  number:           number;
  sort:             Sort;
  first:            boolean;
  numberOfElements: number;
  empty:            boolean;
}

export interface Property {
  id:              number;
  name:            string;
  phone:           string;
  description:     string;
  location:        string;
  logo:            string;
  address:         string;
  images:          string[];
  email:           string;
  commerceType:    string;
  website:         string;
  available:       boolean;
  availableTables: number;
  openingHours:    string;
  closingHours:    string;
  open:            boolean;
}

export interface Pageable {
  sort:       Sort;
  offset:     number;
  pageNumber: number;
  pageSize:   number;
  paged:      boolean;
  unpaged:    boolean;
}

export interface Sort {
  empty:    boolean;
  sorted:   boolean;
  unsorted: boolean;
}
